// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzhuGIyX3pBJpAbNCFcoipBDiJD6i4LA',
    appId: '1:514220075958:web:b3ccc15faea98ad3fe2f17',
    messagingSenderId: '514220075958',
    projectId: 'lvl-stream',
    authDomain: 'lvl-stream.firebaseapp.com',
    storageBucket: 'lvl-stream.appspot.com',
    measurementId: 'G-080MXP60Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxReweoRbv7pNhi6j0RXPJqZ63fNiSKkA',
    appId: '1:514220075958:android:73143a60f577b144fe2f17',
    messagingSenderId: '514220075958',
    projectId: 'lvl-stream',
    storageBucket: 'lvl-stream.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFlheVcRbCPhH7BQN-KzGS_Jla5KfXOPo',
    appId: '1:514220075958:ios:a4406f8fe74599e3fe2f17',
    messagingSenderId: '514220075958',
    projectId: 'lvl-stream',
    storageBucket: 'lvl-stream.appspot.com',
    androidClientId: '514220075958-jbv1b5kaac1p8nmgqo0hdi5mq8he7ono.apps.googleusercontent.com',
    iosClientId: '514220075958-9kjfpk2st4gnbennfv659e1k297bacvd.apps.googleusercontent.com',
    iosBundleId: 'com.streamer.lvl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFlheVcRbCPhH7BQN-KzGS_Jla5KfXOPo',
    appId: '1:514220075958:ios:a4406f8fe74599e3fe2f17',
    messagingSenderId: '514220075958',
    projectId: 'lvl-stream',
    storageBucket: 'lvl-stream.appspot.com',
    androidClientId: '514220075958-jbv1b5kaac1p8nmgqo0hdi5mq8he7ono.apps.googleusercontent.com',
    iosClientId: '514220075958-9kjfpk2st4gnbennfv659e1k297bacvd.apps.googleusercontent.com',
    iosBundleId: 'com.streamer.lvl',
  );
}
